# Generated by Django 4.2.7 on 2025-12-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_upcomingevents_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.TextField()),
                ('number_of_event', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TourCategoriesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.tourcategories')),
            ],
        ),
    ]
