# Generated by Django 4.2.7 on 2025-12-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tourcategories_tourcategoriesimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourlatestblogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs_title', models.CharField(max_length=255)),
                ('seo_url', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ourlatestblogsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.ourlatestblogs')),
            ],
        ),
    ]
