# Generated by Django 4.2.7 on 2025-12-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ourlatestblogs_ourlatestblogsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=100)),
                ('travel_type', models.CharField(max_length=50)),
                ('transport_required', models.CharField(max_length=50)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ourlatestblogsimage',
            old_name='event',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='ourlatestblogs',
            name='seo_url',
            field=models.CharField(max_length=255),
        ),
    ]
