# Generated by Django 4.2.7 on 2025-12-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_travelenquiry_rename_event_ourlatestblogsimage_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactfrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
