# Generated by Django 4.2.7 on 2025-12-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contactfrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssokeywords',
            old_name='meta_discription',
            new_name='Meta_Discription',
        ),
        migrations.RenameField(
            model_name='ssokeywords',
            old_name='meta_title',
            new_name='Meta_Keywords',
        ),
        migrations.AddField(
            model_name='ssokeywords',
            name='Header_Tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ssokeywords',
            name='Meta_Title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssokeywords',
            name='Page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
