# Generated by Django 4.2.7 on 2025-12-11 13:33

from django.db import migrations, models
import django.utils.timezone
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_meta_discription_ssokeywords_meta_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourlatestblogs',
            name='author_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='author_name',
            field=models.CharField(default='xyz', max_length=255),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='category',
            field=models.CharField(default='xyz', max_length=250),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='meta_keywords',
            field=models.CharField(default='xyz', max_length=250),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='title',
            field=models.CharField(default='xyz', max_length=150),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ourlatestblogs',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ourlatestblogs',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
