# Generated by Django 4.2.7 on 2025-12-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ourlatestblogs_author_bio_ourlatestblogs_author_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SsoKeywords',
            new_name='SeoKeywords',
        ),
    ]
